import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronRight, CircleHelp, Crosshair, Film, Layers3, Maximize2, Pause, Play, RotateCcw, ShieldCheck, Upload, X } from 'lucide-react';
import { createDemo } from './core/demo';
import { playerMetrics, stateAt, type Analysis } from './core/model';
import { analyzeVideo } from './core/analyze';
import Pitch from './components/Pitch';
const demo=createDemo();
const clock=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
export default function App(){
 const [analysis,setAnalysis]=useState<Analysis>(demo),[time,setTime]=useState(7),[playing,setPlaying]=useState(false),[rate,setRate]=useState(1),[selected,setSelected]=useState(9),[trails,setTrails]=useState(true),[shape,setShape]=useState(true),[heat,setHeat]=useState(false),[modal,setModal]=useState<'upload'|'about'|null>(null),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[videoUrl,setVideoUrl]=useState(''),[tab,setTab]=useState<'moments'|'players'>('moments');
 const input=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),abort=useRef<AbortController|null>(null),workspace=useRef<HTMLDivElement>(null);
 const local=analysis.source==='local',state=useMemo(()=>stateAt(analysis.frames,time),[analysis,time]);
 const metrics=useMemo(()=>playerMetrics(analysis.frames,selected,time),[analysis,selected,time]);
 useEffect(()=>()=>{if(videoUrl)URL.revokeObjectURL(videoUrl);},[videoUrl]);
 useEffect(()=>()=>abort.current?.abort(),[]);
 useEffect(()=>{if(!playing||local)return;let prev=performance.now();let id=0;const tick=(now:number)=>{const dt=(now-prev)/1000;prev=now;setTime(t=>{const next=t+dt*rate;if(next>=analysis.duration){setPlaying(false);return analysis.duration;}return next;});id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing,rate,local,analysis.duration]);
 useEffect(()=>{if(!video.current)return;video.current.playbackRate=rate;if(playing)void video.current.play().catch(()=>{setPlaying(false);setError('Playback could not start. Try another video format.');});else video.current.pause();},[playing,rate,videoUrl]);
 const seek=(t:number)=>{setTime(t);if(video.current)video.current.currentTime=t;};
 const togglePlay=()=>{if(time>=analysis.duration)seek(0);setPlaying(p=>!p);};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(['INPUT','BUTTON','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName)||modal)return;if(e.code==='Space'){e.preventDefault();togglePlay();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 async function upload(file:File){setError('');setPlaying(false);setProgress(0);const controller=new AbortController();abort.current=controller;try{const result=await analyzeVideo(file,setProgress,controller.signal);setVideoUrl(URL.createObjectURL(file));setAnalysis(result);setTime(0);setSelected(result.frames[0]?.players[0]?.id??1);setModal(null);}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{setProgress(null);abort.current=null;if(input.current)input.current.value='';}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({...analysis,schemaVersion:1,coordinates:local?'normalized-image':'normalized-pitch',judgment:'deterministic-heuristics'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pitchstate-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const props={frames:analysis.frames,time,selected,onSelect:setSelected,trails,shape,heat,local};
 return <><header className="header"><a className="brand" href="./"><span className="brand-icon"><Activity size={22}/></span>PitchState<span className="beta">LAB</span></a><nav><span className="nav-active">Playground</span><button onClick={()=>setModal('about')}>How it works <ArrowRight size={14}/></button></nav><div className="header-right"><span className="privacy"><span className="status-dot"/> Local-first analysis</span><a href="https://github.com/KennyMx/PitchState" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
 <main><section className="intro"><div><div className="eyebrow">THE SOCCER ANALYSIS PLAYGROUND</div><h1>See the game beneath the game<span>.</span></h1><p>Every movement tells a story. Explore how a play unfolds.</p></div><button className="primary" onClick={()=>{setError('');setModal('upload');}}><Upload size={16}/> Upload a clip</button></section>
 <div className="workspace" ref={workspace}><div className="workspace-bar"><div className="clip-title"><span className="clip-icon"><Film size={18}/></span><div><strong>{analysis.name}</strong><span>{local?'Your clip · experimental tracking':'Example 01 · a transition through the left channel'}</span></div></div><div className="workspace-meta"><span className="tag">{local?'LOCAL CLIP':'SIMULATED PLAY'}</span><span>{clock(analysis.duration)} <span className="muted">/</span> {local?'5':'10'} Hz</span><button className="icon-button" aria-label="Export analysis JSON" onClick={exportData}><ArrowDownToLine size={17}/></button></div></div>
 <div className="view-grid"><section className="main-view"><div className="view-top"><span><span className="status-dot"/>{local?'ORIGINAL FOOTAGE':'TACTICAL REPLAY'}</span><span>{local?'On-device processing':'Illustrative sequence · not match footage'}</span></div><div className="stage">{local?<video ref={video} src={videoUrl} playsInline onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)} onError={()=>setError('The browser cannot play this video. Try H.264 MP4.')} />:<><div className="stadium"><div className="stadium-label">PITCHSTATE <span>EXPERIMENTAL FOOTBALL INTELLIGENCE</span> PITCHSTATE</div><Pitch {...props} perspective/></div><div className="scoreboard"><b>HOME</b><span>0 — 0</span><b>AWAY</b><em>{clock(time)}</em></div><div className="direction">ATTACKING DIRECTION <ArrowRight size={20}/></div></>}
 <div className="stage-bottom"><span className="small-tag"><Crosshair size={13}/>{state.frame.players.length} player {local?'candidates':'positions'}</span><button className="icon-button" aria-label="Fullscreen workspace" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void workspace.current?.requestFullscreen?.().catch(()=>{});}}><Maximize2 size={16}/></button></div></div><div className="view-caption"><span><span className="legend home"/>Home <span className="legend away"/>Away <span className="legend ball"/>Ball</span><span>{local?'Red / blue kit baseline':'Select a player to explore their movement'} <Crosshair size={12}/></span></div></section>
 <section className="map-view"><div className="view-top"><span><Layers3 size={14}/> {local?'CAMERA-SPACE MAP':'PITCH RECONSTRUCTION'}</span><span className="live-label">SYNCED</span></div><div className="map-wrap"><Pitch {...props}/></div><div className="map-caption"><span>{local?'Uncalibrated · image coordinates':'Top-down · normalized pitch'}</span><ArrowRight size={16}/></div></section></div>
 <div className="transport"><button className="play-button" onClick={togglePlay} aria-label={playing?'Pause':'Play'}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button className="icon-button" aria-label="Restart" onClick={()=>seek(0)}><RotateCcw size={15}/></button><span className="time">{clock(time)}<span> / {clock(analysis.duration)}</span></span><div className="scrubber"><input aria-label="Playback position" type="range" min="0" max={analysis.duration} step=".05" value={time} onChange={e=>seek(+e.target.value)} style={{background:`linear-gradient(to right, #c4ee83 ${time/analysis.duration*100}%, #343e37 ${time/analysis.duration*100}%)`}}/><div className="timeline-dots">{analysis.events.map((e,i)=><button key={i} style={{left:`${e.time/analysis.duration*100}%`}} onClick={()=>seek(e.time)} aria-label={`Seek to ${e.kind} at ${clock(e.time)}`} title={e.kind}/>)}</div></div><select aria-label="Playback speed" value={rate} onChange={e=>setRate(+e.target.value)}><option value=".5">0.5×</option><option value="1">1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></div>
 <div className="layer-bar"><span className="layer-title">VIEW LAYERS</span>{[{name:'Movement trails',value:trails,set:setTrails},{name:'Team shape',value:shape,set:setShape},{name:'Player heatmap',value:heat,set:setHeat}].map(layer=><button key={layer.name} className={layer.value?'layer enabled':'layer'} aria-pressed={layer.value} onClick={()=>layer.set(!layer.value)}><span className="checkbox">{layer.value&&<Check size={11}/>}</span>{layer.name}</button>)}<span className="keyboard">Space to play / pause</span></div></div>
 <div className="insights-grid"><section className="card state-card"><div className="card-heading"><h2><Activity size={16}/> Game state</h2><span className="tiny">AT {clock(time)}</span></div><div className="phase"><span className="status-dot"/>{state.phase}<span className="heuristic">HEURISTIC</span></div><p className="state-detail">{local?'Player positions are image-space estimates. Ball and tactical judgments await a validated detector.':state.phase==='Quick progression'?'Home is moving the ball forward quickly. Watch the space opening behind the midfield line.':state.phase==='Under pressure'?'Opponents are closing the space around the ball. Watch the supporting passing options.':'Watch the distances between players as the shape adapts to the ball.'}</p><div className="state-stats"><div><span>POSSESSION ESTIMATE</span><strong>{state.owner?state.owner.team==='home'?'Home':'Away':'Unknown'} {state.owner&&<i className={`legend ${state.owner.team}`}/>}</strong></div><div><span>{local?'IMAGE WIDTH':'TEAM WIDTH'}</span><strong>{state.width.toFixed(0)}<small>{local?'%':'% pitch'}</small></strong></div><div><span>NEARBY OPPONENTS</span><strong>{state.owner?state.pressure:'—'}<small> within 12 units</small></strong></div></div><div className="card-note"><ShieldCheck size={13}/> {local?'Low-confidence observations · review visually':'Rule-based signals · inspect the evidence below'}</div></section>
 <section className="card moments-card"><div className="card-heading"><div className="tabs"><button className={tab==='moments'?'active':''} onClick={()=>setTab('moments')}>Key moments <span>{analysis.events.length}</span></button><button className={tab==='players'?'active':''} onClick={()=>setTab('players')}>Player focus</button></div><span className="tiny">{tab==='moments'?'CLICK TO EXPLORE':`PLAYER ${selected}`}</span></div>{tab==='moments'?<div className="moments">{analysis.events.length?analysis.events.map((event,i)=><button className={`moment ${event.time<=time?'revealed':''}`} key={i} onClick={()=>seek(event.time+.6)}><span className="moment-time">{clock(event.time)}</span><span className="event-line"/><span className="moment-text"><strong>{event.kind}</strong><small>{event.detail}</small></span><ChevronRight size={15}/></button>):<div className="empty"><Crosshair size={23}/><div><strong>Positions first. Meaning next.</strong><p>No tactical events are inferred without ball evidence. Explore detected players in Player focus.</p></div></div>}</div>:<div className="player-focus"><div className="player-picker"><label htmlFor="player">Tracked player</label><select id="player" value={selected} onChange={e=>setSelected(+e.target.value)}>{state.frame.players.map(p=><option key={p.id} value={p.id}>{p.team} · #{p.id}</option>)}</select></div><div className="player-numbers"><div><strong>{local?'—':metrics.speed.toFixed(1)}<small>km/h</small></strong><span>Current speed</span></div><div><strong>{local?'—':metrics.distance.toFixed(1)}<small>m</small></strong><span>Distance covered</span></div></div><p>{local?'Physical measurements require pitch calibration. IDs may change during occlusion.':'Simulated measurements on a 105 × 68 m pitch. Select a marker on either view to follow that player.'}</p></div>}</section></div>
 <footer><span className="footer-brand">PitchState <span>A different perspective on the beautiful game.</span></span><button onClick={()=>setModal('about')}><CircleHelp size={14}/> About this experiment</button></footer>
 </main>{error&&!modal&&<div className="toast" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&progress===null)setModal(null);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>{abort.current?.abort();setModal(null);}}><X size={20}/></button>{modal==='upload'?<><div className="modal-symbol"><Upload size={25}/></div><div className="eyebrow">BRING YOUR OWN PLAY</div><h2 id="modal-title">Your clip. A new perspective.</h2><p>Experimental red / blue kit tracking, processed entirely in your browser. Use a stable, wide-angle clip for the best results.</p><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(progress===null&&e.dataTransfer.files[0])void upload(e.dataTransfer.files[0]);}}><Film size={30}/><strong>{progress===null?'Drop a soccer clip here':`Reading the play… ${progress}%`}</strong>{progress===null?<><span>MP4 or WebM · up to 60 seconds · 100 MB max</span><button className="primary" onClick={()=>input.current?.click()}>Choose video <ArrowRight size={16}/></button></>:<><progress value={progress} max="100"/><button onClick={()=>abort.current?.abort()}>Cancel analysis</button></>}<input ref={input} type="file" accept="video/mp4,video/webm,video/quicktime" hidden onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/></div>{error&&<p className="error" role="alert">{error}</p>}<div className="upload-note"><ShieldCheck size={17}/><span>Your video never leaves this device. This baseline detects kit colors, not player identities or the ball. Camera motion and other colors reduce accuracy.</span></div><button className="demo-link" disabled={progress!==null} onClick={()=>{setAnalysis(demo);setVideoUrl('');setTime(7);setSelected(9);setModal(null);}}>Explore the simulated example <ArrowRight size={15}/></button></>:<><div className="eyebrow">BUILT TO EXPLORE</div><h2 id="modal-title">A changing game. A changing state.</h2><p>PitchState turns timestamped observations into a replayable view of the game.</p><div className="about-step"><b>01</b><div><h3>Observe the movement</h3><p>The example uses simulated positions. Your clips use a lightweight local kit-color detector and temporal association.</p></div></div><div className="about-step"><b>02</b><div><h3>Maintain the state</h3><p>Positions, movement history and team geometry update with the playhead. Uploads stay in camera coordinates until calibrated.</p></div></div><div className="about-step"><b>03</b><div><h3>Make the evidence visible</h3><p>Tactical rules use ball proximity and progression, with persistence and cooldowns. Jev is a future optional judge of structured state; it is not connected in this version.</p></div></div><button className="primary" onClick={()=>setModal(null)}>Explore the playground <ArrowRight size={16}/></button></>}</section></div>}</>;
}
